### ISSUE TITLE
Filter «CSS import (CSS)» causes a blank page in BE

### ISSUE THREAD

**Issue by rflx** [bit3/contao-assetic#8]
If i'll try to add the filter «CSS import (CSS)» in assetic, Contao 3.5.0 leaves me with a blank page error. Can someone reproduce it?

**Comment by dmolineus** [comment]
What do you get if you enable `displayErrors` in the settings?

**Comment by rflx** [comment]
Hi dmolineus

this is what i get with `displayErrors` enabled

```
Fatal error: Call to a member function next() on null in /composer/vendor/bit3/contao-assetic/src/ContaoAssetic/DataContainer/AsseticFilter.php on line 57
```

**Comment by dmolineus** [comment]
The issue is clear, can be fixed really simple.

I guess it's Assetics 1.x which you use, am I right? That's gonna be tricky as I got the repository without any code for 1.0.

**Comment by rflx** [comment]
I think its Assetics 1.x, it will be delivered with Theme+  4.4.5.

**Comment by fritzmg** [comment]
> I guess it's Assetics 1.x which you use, am I right? That's gonna be tricky as I got the repository without any code for 1.0.

netzmacht/contao-theme-plus `4.4.5` requires `"bit3/contao-assetic":"~1"`: https://github.com/netzmacht/contao-theme-plus/blob/4.4.5/composer.json#L33

**Comment by dmolineus** [comment]
There is a new branch support/1.x which contains a fix for it. Please install it and give a feedback if it solves the issue.

**Comment by rflx** [comment]
Hi @dmolineus,
sorry for my late reply and thx for the fix. It solves the issue i mentioned above.

Cheers

**Comment by dmolineus** [comment]
Thanks for the feedback. Just release version 1.4.1.
